id = "52521803-fd21-4b40-a4e5-6801b823d59d"
created_at = "2026-04-29T09:56:44.116673300+00:00"
title = "viewer-api: auth + middleware + error"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/auth-middleware"
type = "specification"
