id = "b3362691-09a0-4028-8daa-13b4c4102c15"
created_at = "2026-04-29T09:57:16.264288600+00:00"
title = "viewer-api: layout components"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/components/layout"
type = "specification"
