id = "3fa36e9e-b097-4566-90e4-7d5f8053cd55"
created_at = "2026-04-27T09:36:40.363222500+00:00"
title = "configuration"
state = "draft"
component = "viewer-ctl"
parent = "b7ac0b69-ed06-473a-8fbe-0058a769bf40"
scope = "internal"
slug = "viewer-ctl/config"
type = "specification"
