id = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
created_at = "2026-04-29T09:56:35.878671200+00:00"
title = "viewer-api: demo-viewer"
state = "draft"
component = "viewer-api"
scope = "public"
slug = "viewer-api/demo-viewer"
type = "specification"
