id = "54800731-e07f-4fb2-8802-fd7d2acc8c05"
created_at = "2026-04-29T09:56:52.942522+00:00"
title = "viewer-api: SSE streaming"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/sse"
type = "specification"
