id = "afe17aef-793e-419f-93c1-568bf10a2955"
created_at = "2026-04-27T09:37:18.474586200+00:00"
title = "install layout"
state = "draft"
component = "viewer-ctl"
parent = "b7ac0b69-ed06-473a-8fbe-0058a769bf40"
scope = "public"
slug = "viewer-ctl/install-layout"
type = "specification"
