id = "479e226a-b4ef-4e30-ade0-ebdabbf956ed"
created_at = "2026-04-27T18:22:53.945009400+00:00"
title = "viewer-api: WASM tracing file sink"
state = "draft"
component = "viewer-api"
parent = "b06c9df8-2866-433a-af73-ae9b1f4a0f0a"
scope = "public"
slug = "viewer-api/tracing/file-sink"
type = "specification"
