id = "a6fd15f6-f9c3-407a-af99-3febee5b2557"
created_at = "2026-04-30T11:58:53.253556700+00:00"
title = "[doc-viewer][P6] (Deferred) Migrate doc-viewer onto shared viewer-api"
state = "new"
type = "tracker-improvement"
