id = "baaa35ff-4eb6-4288-b4d3-257311b98aa4"
created_at = "2026-04-29T09:57:51.630739200+00:00"
title = "viewer-api: store primitives"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/store-primitives"
type = "specification"
