id = "2e56d63e-c53a-45a0-a984-088b3f9da19a"
created_at = "2026-05-12T17:35:30.454692900+00:00"
title = "viewer-api: keyboard interaction model"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/keyboard-interaction-model"
type = "specification"
