id = "bce0d2fb-8ac3-4be3-af42-47f5b6928caa"
created_at = "2026-03-27T23:40:16.036060800+00:00"
title = "Impl: Extract HypergraphViewCore to viewer-api as primary graph component"
state = "done"
depends_on = ["20c4d807-042f-4c4b-a683-3d84658094c3"]
type = "tracker-improvement"
