id = "348e17f7-23a8-4e11-bbb3-224cf0bbe9d6"
created_at = "2026-04-29T09:57:25.892475+00:00"
title = "viewer-api: TabBar"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/components/tab-bar"
type = "specification"
