id = "c23166c7-2315-4b89-9160-cde7df3086e6"
created_at = "2026-04-27T09:36:56.278806200+00:00"
title = "frontend lifecycle"
state = "draft"
component = "viewer-ctl"
parent = "b7ac0b69-ed06-473a-8fbe-0058a769bf40"
scope = "internal"
slug = "viewer-ctl/lifecycle/frontend"
type = "specification"
