# App name
name = "viewer-api-dioxus"

# Build output path
out_dir = "dist"

# Static assets directory
asset_dir = "public"

[web.app]
title = "Viewer API — Dioxus"

[web.watcher]
# Regenerate the index.html on each rebuild
reload_html = true
# Watch src and public dirs for changes
watch_path = ["src", "public"]

[web.resource]
style = ["viewer-api.css"]
script = []

[web.resource.dev]
style = []
script = []
