id = "351e65fe-0629-4a0f-9c19-27dabb36b72f"
created_at = "2026-04-27T09:36:50.936429300+00:00"
title = "server lifecycle"
state = "draft"
component = "viewer-ctl"
parent = "b7ac0b69-ed06-473a-8fbe-0058a769bf40"
scope = "internal"
slug = "viewer-ctl/lifecycle/server"
type = "specification"
