id = "4dafde12-e894-43d7-aa65-cda9a072be27"
created_at = "2026-04-27T09:36:45.778140+00:00"
title = "command-line interface"
state = "draft"
component = "viewer-ctl"
parent = "b7ac0b69-ed06-473a-8fbe-0058a769bf40"
scope = "public"
slug = "viewer-ctl/cli"
type = "specification"
