id = "51c69e48-c8a1-4d45-b050-e06671fe7d71"
created_at = "2026-04-29T09:56:57.327975600+00:00"
title = "viewer-api: session"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/session"
type = "specification"
