id = "f153483c-f984-4564-94ac-36234b5cbe3f"
created_at = "2026-04-29T09:57:41.346558600+00:00"
title = "viewer-api: WebGPU overlay"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/effects/wgpu-overlay"
type = "specification"
