id = "7b43dfd1-39aa-4585-b5fe-dc57c6d57eba"
created_at = "2026-04-29T09:57:36.087277400+00:00"
title = "viewer-api: icons + Spinner"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/components/icons-spinner"
type = "specification"
