id = "8bf5edd2-4fe6-4580-ac87-73843f0206f0"
created_at = "2026-04-30T11:58:52.924945200+00:00"
title = "[viewer-api][P3] Widget extensions: TreeNode rich tooltip, mobile sidebar audit, HeaderActions"
state = "done"
type = "tracker-improvement"
