id = "4f14356f-c4bd-4554-be1e-35361de241da"
created_at = "2026-04-29T09:57:46.484960500+00:00"
title = "viewer-api: Graph3D"
state = "draft"
component = "viewer-api"
parent = "4c3b62b4-1198-4ce2-9ef6-df530f38297e"
scope = "public"
slug = "viewer-api/components/graph3d"
type = "specification"
